export const commonPropertiesValuesAbreviations = {
    // Position values
    "ABS": "absolute",
    "REL": "relative",
    "FIX": "fixed",
    "STA": "static",
    "STI": "sticky",
    
    // Display values
    "BLO": "block",
    "INL": "inline",
    "IBL": "inline-block",
    "FLX": "flex",
    "GRI": "grid",
    "NON": "none",
    "TAB": "table",
    "TAC": "table-cell",
    "TAR": "table-row",
    "CNT": "contents",
    "LST": "list-item",
    "IFL": "inline-flex",
    "IGR": "inline-grid",
    "ITB": "inline-table",
    
    // Flex/Grid values
    "FST": "flex-start",
    "FEN": "flex-end",
    "CEN": "center",
    "SBE": "space-between",
    "SAR": "space-around",
    "SEV": "space-evenly",
    "STR": "stretch",
    "BAS": "baseline",
    "COL": "column",
    "ROW": "row",
    "CRE": "column-reverse",
    "RRE": "row-reverse",
    "WRA": "wrap",
    "NOW": "nowrap",
    "WRE": "wrap-reverse",
    
    // Alignment values
    "JUS": "justify",
    "SRT": "start",
    "END": "end",
    "LEF": "left",
    "RIG": "right",
    "TOP": "top",
    "BOT": "bottom",
    
    // Font values
    "BOL": "bold",
    "BOR": "bolder",
    "LIG": "lighter",
    "NOR": "normal",
    "ITA": "italic",
    "OBL": "oblique",
    "SMC": "small-caps",
    "CAP": "capitalize",
    "UPP": "uppercase",
    "LOW": "lowercase",
    "THI": "thin",
    "MED": "medium",
    "THK": "thick",    "SER": "serif",
    "SAN": "sans-serif",
    "MON": "monospace",
    "CUR": "cursive",
    "FAN": "fantasy",
    
    // Text decoration values
    "UND": "underline",
    "OVE": "overline",
    "LTH": "line-through",
    "STK": "strikethrough",
    
    // Border style values
    "SOL": "solid",
    "DAS": "dashed",
    "DOT": "dotted",
    "DOU": "double",
    "GRO": "groove",
    "RID": "ridge",
    "INS": "inset",
    "OUT": "outset",
    "HID": "hidden",
    
    // List style values
    "DIS": "disc",
    "CIR": "circle",
    "SQU": "square",
    "DEC": "decimal",
    "LRO": "lower-roman",
    "URO": "upper-roman",
    "LAL": "lower-alpha",
    "UAL": "upper-alpha",
    "LAT": "lower-latin",
    "ULA": "upper-latin",
    "ARM": "armenian",
    "GEO": "georgian",
    "CJK": "cjk-ideographic",
    "HEB": "hebrew",
    "HIR": "hiragana",
    "KAT": "katakana",
    
    // Background values
    "NRP": "no-repeat",
    "REP": "repeat",
    "REX": "repeat-x",
    "REY": "repeat-y",
    "ROU": "round",
    "SPA": "space",
    "COV": "cover",
    "COT": "contain",
    "SCR": "scroll",
    "BFX": "fixed",
    
    // Cursor values
    "POI": "pointer",
    "DEF": "default",
    "TEX": "text",
    "MOV": "move",
    "WAI": "wait",
    "HEL": "help",
    "CRO": "crosshair",
    "PRO": "progress",
    "NAL": "not-allowed",
    "ZIN": "zoom-in",
    "ZOU": "zoom-out",
    "GRA": "grab",
    "GRB": "grabbing",
    "ERS": "e-resize",
    "WRS": "w-resize",
    "NRS": "n-resize",
    "SRS": "s-resize",
    "NER": "ne-resize",
    "NWR": "nw-resize",
    "SRZ": "se-resize",
    "SWR": "sw-resize",
    "EWR": "ew-resize",
    "NSR": "ns-resize",
    "NES": "nesw-resize",
    "NWS": "nwse-resize",
    "CLR": "col-resize",
    "RWR": "row-resize",
    "ALL": "all-scroll",
    "VTE": "vertical-text",
    "CEL": "cell",
    "CME": "context-menu",
    "COP": "copy",
    "AUT": "auto",
    
    // Animation/Transition values
    "EAS": "ease",
    "EAI": "ease-in",
    "EAO": "ease-out",
    "EIO": "ease-in-out",
    "LIN": "linear",
    "INF": "infinite",
    "ALT": "alternate",
    "ALR": "alternate-reverse",
    "REV": "reverse",
    "FOR": "forwards",
    "BAC": "backwards",
    "BTH": "both",
    "RUN": "running",
    "PAU": "paused",
    
    // Overflow values
    "VIS": "visible",
    "HDD": "hidden",
    "SCL": "scroll",
    "ATU": "auto",
    "CLP": "clip",
      // White space values
    "NWP": "nowrap",
    "PRE": "pre",
    "PWR": "pre-wrap",
    "PLI": "pre-line",
    "BSP": "break-spaces",
    
    // Word break values
    "KEE": "keep-all",
    "BRA": "break-all",
    "BRW": "break-word",
    
    // Transform values
    "PR3": "preserve-3d",
    "FLA": "flat",
    
    // Box sizing values
    "CBX": "content-box",
    "BBX": "border-box",
      // Clear/Float values
    "CLB": "both",
    "CLL": "left",
    "CLT": "right",
    "CLN": "none",
    
    // Table values
    "TBC": "collapse",
    "TBS": "separate",
    
    // Resize values
    "RSB": "both",
    "RSH": "horizontal",
    "RSV": "vertical",
    "RSN": "none",
    
    // User select values
    "USN": "none",
    "UST": "text",
    "USA": "all",
    "USU": "auto",
    
    // Appearance values
    "APN": "none",
    "APA": "auto",
    "APB": "button",
    "APC": "checkbox",
    "APR": "radio",
    "APT": "textfield",
    "APM": "menulist",
    
    // Miscellaneous values
    "ALV": "all",
    "AUV": "auto",
    "INI": "initial",
    "INH": "inherit",
    "UNS": "unset",
    "RVT": "revert",
    "TRA": "transparent",
    "CCL": "currentColor",
    
    // Filter values
    "BLU": "blur",
    "BRI": "brightness",
    "CON": "contrast",
    "DRO": "drop-shadow",
    "GRY": "grayscale",
    "HUR": "hue-rotate",
    "INV": "invert",
    "OPA": "opacity",
    "SAT": "saturate",
    "SEP": "sepia",
    
    // Mix blend mode values
    "MBN": "normal",
    "MBM": "multiply",
    "MBS": "screen",
    "MBO": "overlay",
    "MBD": "darken",
    "MBL": "lighten",
    "MCD": "color-dodge",
    "MCB": "color-burn",
    "MHL": "hard-light",
    "MSL": "soft-light",
    "MDF": "difference",
    "MEX": "exclusion",
    "MHU": "hue",
    "MSA": "saturation",
    "MCO": "color",
    "MLU": "luminosity",
    
    // Object fit values
    "OFI": "fill",
    "OCN": "contain",
    "OCV": "cover",
    "ONO": "none",
    "OSD": "scale-down"
}