export const cssNamesParsed = {
  d: 'display',
  ta: 'text-align',
  tde: 'text-decoration',
  w: 'width',
  h: 'height',
  wmn: 'min-width',
  hmn: 'min-height',
  wmx: 'max-width',
  hmx: 'max-height',
  minw: 'min-width',
  minh: 'min-height',
  maxw: 'max-width',
  maxh: 'max-height',
  rounded: 'border-radius',
  r: 'border-radius',
  rs: ['border-top-left-radius', 'border-bottom-left-radius'],
  re: ['border-top-right-radius', 'border-bottom-right-radius'],
  rt: ['border-top-left-radius', 'border-top-right-radius'],
  rb: ['border-bottom-left-radius', 'border-bottom-right-radius'],
  rst: 'border-top-left-radius',
  ret: 'border-top-right-radius',
  rsb: 'border-bottom-left-radius',
  reb: 'border-bottom-right-radius',
  z: 'z-index',
  o: 'opacity',
  pos: 'position',
  t: 'top',
  bot: 'bottom',
  b: 'bottom',
  start: 'left',
  s: 'left',
  end: 'right',
  e: 'right',
  fs: 'font-size',
  lh: 'line-height',
  g: 'gap',
  p: 'padding',
  pt: 'padding-top',
  pb: 'padding-bottom',
  ps: 'padding-left',
  pe: 'padding-right',
  py: ['padding-top', 'padding-bottom'],
  px: ['padding-left', 'padding-right'],
  m: 'margin',
  mt: 'margin-top',
  mb: 'margin-bottom',
  ms: 'margin-left',
  me: 'margin-right',
  my: ['margin-top', 'margin-bottom'],
  mx: ['margin-left', 'margin-right'],
  bw: 'border-width',
  bwt: 'border-top-width',
  bwb: 'border-bottom-width',
  bws: 'border-left-width',
  bwe: 'border-right-width',
  bwy: ['border-top-width', 'border-bottom-width'],
  bwx: ['border-left-width', 'border-right-width'],
  borderStylet: 'border-top-style',
  borderStyleb: 'border-bottom-style',
  borderStyles: 'border-left-style',
  borderStylee: 'border-right-style',
  borderStyley: ['border-top-style', 'border-bottom-style'],
  borderStylex: ['border-left-style', 'border-right-style'],
  bs: 'border-style',
  bst: 'border-top-style',
  bsb: 'border-bottom-style',
  bss: 'border-left-style',
  bse: 'border-right-style',
  bsy: ['border-top-style', 'border-bottom-style'],
  bsx: ['border-left-style', 'border-right-style'],
  borderColort: 'border-top-color',
  borderColorb: 'border-bottom-color',
  borderColors: 'border-left-color',
  borderColore: 'border-right-color',
  borderColory: ['border-top-color', 'border-bottom-color'],
  borderColorx: ['border-left-color', 'border-right-color'],
  bc: 'border-color',
  bct: 'border-top-color',
  bcb: 'border-bottom-color',
  bcs: 'border-left-color',
  bce: 'border-right-color',
  bcy: ['border-top-color', 'border-bottom-color'],
  bcx: ['border-left-color', 'border-right-color'],
  BG: 'background',
  bg: 'background-color',
  bgc: 'background-color',
  bgi: 'background-image',
  bgcl: 'background-clip',
  text: 'color',
  c: 'color',
  bsh: 'box-shadow',
  tsh: 'text-shadow',
  ov: 'overflow',
  ovx: 'overflow-x',
  ovy: 'overflow-y',
};
